### ISSUE TITLE
Change Organization Name to maptimemsp

### ISSUE THREAD

**Issue by mtaylorlong** [maptimemsp/organizers#11]
I'm not sure if this would mess things up, but it's driving me crazy that I named this org _MaptimeMSP_. It should really be _maptime-msp_.

How would y'all feel about letting me rename the org? It might screw up a few existing connections, but I can't imagine they would be difficult to fix. It's easier to do this now than later, and it will make me feel much better.

Yea or nay?

**Comment by geospatialem** [comment]
I think the only repo it would affect would be the NACIS map. Since we are actively receiving PR's and I'm giving a live demo tomorrow I'd recommend waiting for now. I'd also like @fawcett to weigh in, too (he's unavailable until Thurs at the earliest).

I'd say **_nay_** for now, but once things settle down with the NACIS map my answer would change to **_yea_**.

**Comment by mtaylorlong** [comment]
Yeah. I wouldn't want to mess anything up, but if we're interested in changing it, it would probably be easier now than later. Once our NACIS map is shared with the NACIS community, I'm afraid we'll never change it, but since that hasn't happened quite yet, this might be our last chance. I'd also like to know what @fawcett thinks.

**Comment by fawcett** [comment]
I like the idea of getting rid of the mixed case, and agree that is is less painful now rather than later.  Let's do it.

**Comment by geospatialem** [comment]
Cool :sunglasses:! @mtaylorlong, want to make the switch? My demo is over, so I'm on board.

**Comment by mtaylorlong** [comment]
It is done. I just switched the name to maptimemsp (no dash). Don't forget to update your local repos! Keep an eye out for any other broken stuff we haven't though of (surely there's won't be much of that).
